
from os.path import dirname, realpath, join
dir_path = dirname(realpath(__file__))

cube_obj = join(dir_path, 'cube.obj')
light_fs = join(dir_path, 'light.fs')
light_vs = join(dir_path, 'light.vs')
menu_png = join(dir_path, 'menu.png')
object_fs = join(dir_path, 'object.fs')
object_vs = join(dir_path, 'object.vs')
ui_fs = join(dir_path, 'ui.fs')
ui_vs = join(dir_path, 'ui.vs')
sedan_body_obj = join(dir_path, 'sedan_body.obj')
sedan_glass_obj = join(dir_path, 'sedan_glass.obj')
sedan_tires_obj = join(dir_path, 'sedan_tires.obj')
sedan_wheels_obj = join(dir_path, 'sedan_wheels.obj')
square_obj = join(dir_path, 'square.obj')
uv_test_png = join(dir_path, 'uv_test.png')
text_image_png = join(dir_path, 'text image.png')
desert_road_png = join(dir_path, 'desert road.png')
bullet_png = join(dir_path, 'bullet.png')
green_goblin_png = join(dir_path, 'green goblin.png')
rainbow_tornado_png = join(dir_path, 'rainbow_tornado.png')
splat_png = join(dir_path, 'splat.png')
tornado_png = join(dir_path, 'tornado.png')
treasure_png = join(dir_path, 'treasure.png')
window_close_png = join(dir_path, 'window close.png')
window_close_active_png = join(dir_path, 'window close active.png')
fractal_png = join(dir_path, 'fractal.png')
pink_bubbles_png = join(dir_path, 'pink bubbles.png')
depot_png = join(dir_path, 'depot.png')
blue_squares_png = join(dir_path, 'blue squares.png')
red_gloop_png = join(dir_path, 'red gloop.png')
