
from os.path import dirname, realpath, join
dir_path = dirname(realpath(__file__))

cube_obj = join(dir_path, 'cube.obj')
light_fs = join(dir_path, 'light.fs')
light_vs = join(dir_path, 'light.vs')
menu_png = join(dir_path, 'menu.png')
object_fs = join(dir_path, 'object.fs')
object_vs = join(dir_path, 'object.vs')
sedan_body_obj = join(dir_path, 'sedan_body.obj')
sedan_glass_obj = join(dir_path, 'sedan_glass.obj')
square_obj = join(dir_path, 'square.obj')
uv_test_png = join(dir_path, 'uv_test.png')
Menu_Button_png = join(dir_path, 'Menu_Button.png')
desert_road_png = join(dir_path, 'desert road.png')
bullet_png = join(dir_path, 'bullet.png')
green_goblin_png = join(dir_path, 'green goblin.png')
rainbow_tornado_png = join(dir_path, 'rainbow_tornado.png')
splat_png = join(dir_path, 'splat.png')
tornado_png = join(dir_path, 'tornado.png')
treasure_png = join(dir_path, 'treasure.png')
window_close_png = join(dir_path, 'window close.png')
